@startuml sd_getGlobalPlayerStatistics

actor player
participant BlazorFront
participant BlazorBack
participant ScoringApi

player -> BlazorFront : PlayerStatisticsPage
activate BlazorFront
    BlazorFront -> BlazorBack : GetAllGameTypes(PlayerId)
    activate BlazorBack
        BlazorBack --> BlazorFront : List<GameType>()
    deactivate BlazorBack
    BlazorFront -> BlazorFront : Compute

    BlazorFront -> BlazorBack : GetGlobalStatistics(PlayerId)
    activate BlazorBack
        loop GameType
            BlazorBack -> BlazorBack : GetStatistics(PlayerId,GameTypeId)
            activate BlazorBack
                BlazorBack -> ScoringApi : GetGameHistory()
                BlazorBack -> BlazorBack : Compute 
                BlazorBack --> BlazorFront : GameTypesPlayerStatistics
            deactivate BlazorBack
        end
    BlazorFront -> player : show
deactivate BlazorFront


@enduml